output-format: text

inherits:
    - strictness_veryhigh
    - full_pep8
    - no_test_warnings

ignore-patterns:
    - ^docs/
    - ^fec/fec/settings
    - ^fec/wsgi.py
    - ^fec/manage.py
    - ^fec/.*/tests.py
    - ^fec/.*/migrations
    - ^fec/functional_tests/

pylint:
    enable:
        - C0111     # Missing docstring
        - C0112     # Empty docstring
    disable:
        - R0901     # Too many ancestors
        - R0903     # Too few public methods
        - R0904     # Too many public methods

pyflakes:
    enable:
        - FL0007
    disable:
        - F841      # Variable assigned but never used (pylint's is better)

frosted:
    enable:
        - E401
    disable:
        - D203      # 1 blank lines before class docstring
        - E307      # Variable assigned but never used (pylint's is better)
